'use strict';
const $=id=>document.getElementById(id);
const words={
hy:{title:'Նկարի պարզ վերլուծություն',account:'Իմ հաշիվը',admin:'Ադմին · Binance-ի հին ստուգումներ',logout:'Դուրս գալ',safety:'ՄԻԱՅՆ ՎԵՐԼՈՒԾՈՒԹՅՈՒՆ · ԱՎՏՈՄԱՏ ԳՈՐԾԱՐՔՆԵՐ ՉԿԱՆ',intro:'1. Ներբեռնեք գրաֆիկի նոր նկարը։ 2. Նշեք տվյալները։ 3. Ստացեք պարզ բացատրություն։',image:'Գրաֆիկի նկար՝ PNG / JPG / WEBP, մինչև 5 MB',market:'Շուկա՝ ինչպես գրված է նկարում',type:'Շուկայի տեսակ',timeframe:'Մեկ մոմի ժամանակը',expiry:'Գործարքի նախատեսված տևողությունը՝ րոպե',consent:'Համաձայն եմ նկարը ուղարկել Google Gemini-ին։ Նախ կտրել եմ անձնական տվյալները։ Նկարը մեր բազայում չի պահպանվում։',analyze:'Վերլուծել նկարը',result:'Պատասխան',clear:'Մաքրել նկարը և պատասխանը',limitations:'Ինչ է աշխատում, ինչ՝ ոչ',limits:'Սա Pocket Option-ի ուղիղ կապ չէ։ Նկարը չի ցույց տալիս ապագան։ Binance-ի սկանավորումն ու ծանուցումները դադարեցված են, հին տվյալները պահպանված են։ Pocket Option-ի ավտոմատ ծանուցումներ կամ արդյունքի ավտոմատ ստուգում դեռ չկան։ Մոմի ժամանակը և գործարքի ավարտը տարբեր բաներ են։ Սկզբում փորձարկեք demo-ում։',ready:'Նկարի AI-ը կարգավորված է · Binance-ը քնած է',missing:'Նկարի AI-ը միացված չէ․ ադմինը պետք է կարգավորի GEMINI_API_KEY-ը։ Binance-ը քնած է։',busy:'Վերլուծվում է… Պատասխանը նկարում եղած պահի մասին է։',error:'Հարցումը չհաջողվեց։ Փորձեք կրկին։',bad:'Ընտրեք մինչև 5 MB PNG, JPG կամ WEBP նկար։',empty:'Ներբեռնեք նոր, հստակ նկար՝ տեսանելի շուկայի անունով և մոմերի ժամանակով։'},
ru:{title:'Простой анализ изображения',account:'Мой аккаунт',admin:'Админ · прежние проверки Binance',logout:'Выйти',safety:'ТОЛЬКО АНАЛИЗ · БЕЗ АВТОМАТИЧЕСКИХ СДЕЛОК',intro:'1. Загрузите свежий график. 2. Укажите данные. 3. Получите простое объяснение.',image:'График: PNG / JPG / WEBP, до 5 MB',market:'Актив, как на изображении',type:'Тип рынка',timeframe:'Длительность одной свечи',expiry:'Планируемый срок сделки, минуты',consent:'Согласен отправить изображение Google Gemini. Личные данные обрезаны. В нашей базе изображение не сохраняется.',analyze:'Анализировать изображение',result:'Ответ',clear:'Очистить изображение и ответ',limitations:'Возможности и ограничения',limits:'Это не прямое подключение к Pocket Option. Изображение не показывает будущее. Сканирование и уведомления Binance приостановлены, история сохранена. Автоуведомлений и автоматической проверки результатов Pocket Option пока нет. Период свечи не равен сроку сделки. Сначала используйте demo.',ready:'AI настроен · Binance приостановлен',missing:'AI не подключён: администратору нужно настроить GEMINI_API_KEY. Binance приостановлен.',busy:'Анализ… Ответ относится к моменту на изображении.',error:'Запрос не выполнен. Попробуйте снова.',bad:'Выберите PNG, JPG или WEBP до 5 MB.',empty:'Загрузите свежий чёткий график с названием актива и периодом свечей.'},
en:{title:'Simple chart review',account:'My account',admin:'Admin · previous Binance checks',logout:'Log out',safety:'ANALYSIS ONLY · NO AUTOMATIC TRADES',intro:'1. Upload a fresh chart. 2. Enter its details. 3. Get a simple explanation.',image:'Chart: PNG / JPG / WEBP, up to 5 MB',market:'Asset, as shown on the chart',type:'Market type',timeframe:'One candle duration',expiry:'Intended trade expiry, minutes',consent:'I agree to send this image to Google Gemini. I have cropped personal information. The image is not stored in our database.',analyze:'Review image',result:'Answer',clear:'Clear image and answer',limitations:'Capabilities and limitations',limits:'This is not a live Pocket Option connection. A screenshot cannot show the future. Binance scanning and alerts are paused; history is preserved. Pocket Option automatic alerts and outcome verification are not connected. Candle period differs from expiry. Test on demo first.',ready:'Image AI configured · Binance paused',missing:'Image AI is not connected: the administrator must configure GEMINI_API_KEY. Binance is paused.',busy:'Reviewing… The answer concerns the moment shown in the image.',error:'Request failed. Please try again.',bad:'Choose a PNG, JPG or WEBP up to 5 MB.',empty:'Upload a fresh, clear chart with the asset name and candle period visible.'}};
words.hy.consent += ' Անվճար ռեժիմում Google-ը կարող է բովանդակությունն օգտագործել ծառայությունները բարելավելու համար։';
words.ru.consent += ' На бесплатном тарифе Google может использовать содержимое для улучшения продуктов.';
words.en.consent += ' On the free tier, Google may use content to improve its products.';
let lang=localStorage.getItem('trade-language')||'hy';if(!words[lang])lang='hy';
let configured=false,busy=false,imageUrl=null,requestVersion=0;
const t=key=>words[lang][key];
function render(){document.documentElement.lang=lang;$('language').value=lang;document.querySelectorAll('[data-text]').forEach(el=>el.textContent=t(el.dataset.text));$('notice').textContent=t(configured?'ready':'missing');$('submit').disabled=!configured||busy;if(!$('answer').textContent)$('answer').textContent=t('empty');}
$('language').onchange=()=>{const empty=$('answer').textContent===t('empty');lang=$('language').value;localStorage.setItem('trade-language',lang);if(empty)$('answer').textContent=t('empty');render();};
function clear(){requestVersion++;$('chartForm').reset();if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=null;$('preview').removeAttribute('src');$('preview').hidden=true;$('answer').textContent=t('empty');}
$('clear').onclick=clear;
$('chartImage').onchange=()=>{requestVersion++;$('answer').textContent=t('empty');const file=$('chartImage').files[0];if(imageUrl)URL.revokeObjectURL(imageUrl);$('preview').hidden=true;if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){$('chartImage').value='';$('answer').textContent=t('bad');return;}imageUrl=URL.createObjectURL(file);$('preview').src=imageUrl;$('preview').hidden=false;};
$('chartForm').onsubmit=async event=>{event.preventDefault();if(!configured||busy)return;const file=$('chartImage').files[0];if(!file)return;const version=++requestVersion;busy=true;render();$('answer').textContent=t('busy');try{const image=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const response=await fetch('/api/chart-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_data:image,symbol:$('market').value,timeframe:$('candleTime').value,expiry_minutes:Number($('expiry').value),market_type:$('marketType').value,language:lang,consent:$('consent').checked})});if(response.status===401){location.replace('/login');return;}const body=await response.json();if(!response.ok)throw Error(typeof body.detail==='string'?body.detail:t('error'));if(version===requestVersion)$('answer').textContent=body.analysis+'\n\n'+new Date(body.created_at).toLocaleString();}catch(error){if(version===requestVersion)$('answer').textContent=error.message||t('error');}finally{busy=false;render();}};
$('logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.replace('/login');};
render();
fetch('/api/workspace').then(async response=>{if(response.status===401){location.replace('/login');return;}if(!response.ok)throw Error();const data=await response.json();configured=data.vision_configured;render();}).catch(()=>{$('notice').textContent=t('error');});
fetch('/api/account').then(r=>r.json()).then(user=>{$('adminLink').hidden=!user.is_admin;}).catch(()=>{});
